import Euclidean1 = require('davinci-blade/Euclidean1');
import Euclidean2 = require('davinci-blade/Euclidean2');
import Euclidean3 = require('davinci-blade/Euclidean3');
import Rational = require('davinci-blade/Rational');
import Dimensions = require('davinci-blade/Dimensions');
import Unit = require('davinci-blade/Unit');
import Complex = require('davinci-blade/Complex');
import Color = require('davinci-blade/Color');
/**
 * Provides the blade module
 *
 * @module blade
 */
declare var blade: {
    'VERSION': string;
    Color: typeof Color;
    Complex: typeof Complex;
    Euclidean1: typeof Euclidean1;
    Euclidean2: typeof Euclidean2;
    Euclidean3: typeof Euclidean3;
    scalarE3: (w: number, uom?: Unit) => Euclidean3;
    vectorE3: (x: number, y: number, z: number, uom?: Unit) => Euclidean3;
    bivectorE3: (xy: number, yz: number, zx: number, uom?: Unit) => Euclidean3;
    Rational: typeof Rational;
    Dimensions: typeof Dimensions;
    Unit: typeof Unit;
    e2ga: {
        e1: Euclidean2;
        e2: Euclidean2;
        units: {
            ampere: Euclidean2;
            candela: Euclidean2;
            coulomb: Euclidean2;
            farad: Euclidean2;
            foot: Euclidean2;
            henry: Euclidean2;
            hertz: Euclidean2;
            inch: Euclidean2;
            joule: Euclidean2;
            kelvin: Euclidean2;
            kilogram: Euclidean2;
            meter: Euclidean2;
            mile: Euclidean2;
            mole: Euclidean2;
            newton: Euclidean2;
            ohm: Euclidean2;
            pascal: Euclidean2;
            pound: Euclidean2;
            second: Euclidean2;
            siemen: Euclidean2;
            tesla: Euclidean2;
            unity: Euclidean2;
            volt: Euclidean2;
            watt: Euclidean2;
            weber: Euclidean2;
            yard: Euclidean2;
        };
    };
    e3ga: {
        e1: Euclidean3;
        e2: Euclidean3;
        e3: Euclidean3;
        units: {
            ampere: Euclidean3;
            candela: Euclidean3;
            coulomb: Euclidean3;
            farad: Euclidean3;
            foot: Euclidean3;
            henry: Euclidean3;
            hertz: Euclidean3;
            inch: Euclidean3;
            joule: Euclidean3;
            kelvin: Euclidean3;
            kilogram: Euclidean3;
            meter: Euclidean3;
            mile: Euclidean3;
            mole: Euclidean3;
            newton: Euclidean3;
            ohm: Euclidean3;
            pascal: Euclidean3;
            pound: Euclidean3;
            second: Euclidean3;
            siemen: Euclidean3;
            tesla: Euclidean3;
            unity: Euclidean3;
            volt: Euclidean3;
            watt: Euclidean3;
            weber: Euclidean3;
            yard: Euclidean3;
        };
    };
    units: {
        ampere: Unit;
        candela: Unit;
        coulomb: Unit;
        farad: Unit;
        foot: Unit;
        henry: Unit;
        hertz: Unit;
        inch: Unit;
        joule: Unit;
        kelvin: Unit;
        kilogram: Unit;
        meter: Unit;
        mile: Unit;
        mole: Unit;
        newton: Unit;
        ohm: Unit;
        pascal: Unit;
        pound: Unit;
        second: Unit;
        siemen: Unit;
        tesla: Unit;
        unity: Unit;
        volt: Unit;
        watt: Unit;
        weber: Unit;
        yard: Unit;
    };
};
export = blade;
